// <auto-generated />
using ASApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASApi.Migrations
{
    [DbContext(typeof(ASApiContext))]
    [Migration("20230825224104_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            Breed = "Golden Retriever",
                            Name = "Buddy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Breed = "Labrador Retriever",
                            Name = "Molly",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Breed = "Poodle",
                            Name = "Coco",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Breed = "Labrador Retriever",
                            Name = "Charlie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 4,
                            Breed = "Labrador Retriever",
                            Name = "Lucy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 6,
                            Breed = "Golden Retriever",
                            Name = "Bailey",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 7,
                            Breed = "Golden Retriever",
                            Name = "Daisy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 8,
                            Breed = "Pug",
                            Name = "Maggie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 9,
                            Breed = "Pug",
                            Name = "Sophie",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 10,
                            Breed = "Ocicat",
                            Name = "Chloe",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 11,
                            Breed = "Ocicat",
                            Name = "Sadie",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 12,
                            Breed = "Persian",
                            Name = "Lola",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 13,
                            Breed = "Persian",
                            Name = "Zoe",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 14,
                            Breed = "Ragdoll",
                            Name = "Duke",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 15,
                            Breed = "Ragdoll",
                            Name = "Lily",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 16,
                            Age = 16,
                            Breed = "Siamese",
                            Name = "Rocky",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 17,
                            Age = 17,
                            Breed = "Siamese",
                            Name = "Luna",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 18,
                            Age = 18,
                            Breed = "Sphynx",
                            Name = "Harley",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 19,
                            Age = 19,
                            Breed = "Sphynx",
                            Name = "Mia",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 20,
                            Age = 20,
                            Breed = "Sphynx",
                            Name = "Max",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
